version: '3'
services:
  server:
    #image: server
    build:
      context: .
      dockerfile: execute.Dockerfile
    restart: always
    ports:
    - "80:80"

  client:
    #image: client
    build:
      context: .
      dockerfile: client.Dockerfile
    depends_on:
      - server
    ports:
    - "8001:8001"
