---
version: 2.1

jobs:
    test:
        docker:
            - image: carlossamu7/cc1-conservatorio:latest
        steps:
            - checkout
            - run: make tests

workflows:
    build_test:
        jobs:
            - test
