---
name: "Comprobar YAML"
on:
  push:
    paths:
      - 'cc.yaml'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'cc.yaml'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Comprobando cc.yaml"
        run: yamllint cc.yaml
      - name: "Comprobando test-docker-compose.yml"
        run: yamllint .github/workflows/test-docker-compose.yml
      - name: "Comprobando yaml.yml"
        run: yamllint yamllint .github/workflows/yaml.yml
